"""initial_schema

Revision ID: 850c045c6a5e
Revises: 
Create Date: 2026-03-06 13:24:03.770568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850c045c6a5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_username'), 'app_users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_type'), 'audit_logs', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('movement_pattern', sa.String(length=64), nullable=True),
    sa.Column('equipment', sa.String(length=64), nullable=True),
    sa.Column('primary_muscles_json', sa.JSON(), nullable=False),
    sa.Column('progression_mode', sa.String(length=32), nullable=False),
    sa.Column('rep_target_min', sa.Integer(), nullable=False),
    sa.Column('rep_target_max', sa.Integer(), nullable=False),
    sa.Column('load_increment', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_deleted_at'), 'exercises', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=False)
    op.create_table('export_records',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_records_status'), 'export_records', ['status'], unique=False)
    op.create_table('food_items',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('brand', sa.String(length=128), nullable=True),
    sa.Column('serving_name', sa.String(length=64), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('sugar_g', sa.Float(), nullable=False),
    sa.Column('sodium_mg', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_items_deleted_at'), 'food_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_food_items_name'), 'food_items', ['name'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_category'), 'goals', ['category'], unique=False)
    op.create_index(op.f('ix_goals_deleted_at'), 'goals', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_goals_metric_key'), 'goals', ['metric_key'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=12), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('body_hash', sa.String(length=128), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idempotency_records_created_at'), 'idempotency_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_idempotency_records_key'), 'idempotency_records', ['key'], unique=False)
    op.create_index(op.f('ix_idempotency_records_method'), 'idempotency_records', ['method'], unique=False)
    op.create_index(op.f('ix_idempotency_records_path'), 'idempotency_records', ['path'], unique=False)
    op.create_table('insight_snapshots',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insight_snapshots_snapshot_date'), 'insight_snapshots', ['snapshot_date'], unique=False)
    op.create_table('job_records',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('job_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_records_available_at'), 'job_records', ['available_at'], unique=False)
    op.create_index(op.f('ix_job_records_dedupe_key'), 'job_records', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_job_records_job_type'), 'job_records', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_records_status'), 'job_records', ['status'], unique=False)
    op.create_table('meal_templates',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_templates_deleted_at'), 'meal_templates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_meal_templates_name'), 'meal_templates', ['name'], unique=False)
    op.create_table('photo_analysis_drafts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_path', sa.String(length=512), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('candidates_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meal_entry_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_analysis_drafts_status'), 'photo_analysis_drafts', ['status'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('instructions_json', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_deleted_at'), 'recipes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_recipes_name'), 'recipes', ['name'], unique=False)
    op.create_table('routines',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('goal', sa.String(length=128), nullable=True),
    sa.Column('schedule_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routines_deleted_at'), 'routines', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_routines_name'), 'routines', ['name'], unique=False)
    op.create_table('weight_entries',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_entries_deleted_at'), 'weight_entries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_weight_entries_logged_at'), 'weight_entries', ['logged_at'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_prefix'), 'api_keys', ['prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_token_hash'), 'api_keys', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('meal_entries',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meal_type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('template_id', sa.String(length=26), nullable=True),
    sa.Column('recipe_id', sa.String(length=26), nullable=True),
    sa.Column('photo_draft_id', sa.String(length=26), nullable=True),
    sa.Column('total_calories', sa.Float(), nullable=False),
    sa.Column('total_protein_g', sa.Float(), nullable=False),
    sa.Column('total_carbs_g', sa.Float(), nullable=False),
    sa.Column('total_fat_g', sa.Float(), nullable=False),
    sa.Column('total_fiber_g', sa.Float(), nullable=False),
    sa.Column('total_sodium_mg', sa.Float(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photo_draft_id'], ['photo_analysis_drafts.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['meal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_entries_deleted_at'), 'meal_entries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_meal_entries_logged_at'), 'meal_entries', ['logged_at'], unique=False)
    op.create_index(op.f('ix_meal_entries_meal_type'), 'meal_entries', ['meal_type'], unique=False)
    op.create_index(op.f('ix_meal_entries_photo_draft_id'), 'meal_entries', ['photo_draft_id'], unique=False)
    op.create_index(op.f('ix_meal_entries_recipe_id'), 'meal_entries', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_meal_entries_template_id'), 'meal_entries', ['template_id'], unique=False)
    op.create_table('meal_template_items',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('meal_template_id', sa.String(length=26), nullable=False),
    sa.Column('food_id', sa.String(length=26), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('grams', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('sodium_mg', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['meal_template_id'], ['meal_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_template_items_food_id'), 'meal_template_items', ['food_id'], unique=False)
    op.create_index(op.f('ix_meal_template_items_meal_template_id'), 'meal_template_items', ['meal_template_id'], unique=False)
    op.create_table('recipe_items',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('recipe_id', sa.String(length=26), nullable=False),
    sa.Column('food_id', sa.String(length=26), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_items_food_id'), 'recipe_items', ['food_id'], unique=False)
    op.create_index(op.f('ix_recipe_items_recipe_id'), 'recipe_items', ['recipe_id'], unique=False)
    op.create_table('routine_exercises',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('routine_id', sa.String(length=26), nullable=False),
    sa.Column('exercise_id', sa.String(length=26), nullable=False),
    sa.Column('day_label', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps_min', sa.Integer(), nullable=False),
    sa.Column('target_reps_max', sa.Integer(), nullable=False),
    sa.Column('target_rir', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routine_exercises_exercise_id'), 'routine_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_routine_exercises_routine_id'), 'routine_exercises', ['routine_id'], unique=False)
    op.create_table('session_tokens',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_tokens_expires_at'), 'session_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_session_tokens_token_hash'), 'session_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_session_tokens_user_id'), 'session_tokens', ['user_id'], unique=False)
    op.create_table('workout_templates',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('routine_id', sa.String(length=26), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_templates_deleted_at'), 'workout_templates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workout_templates_name'), 'workout_templates', ['name'], unique=False)
    op.create_index(op.f('ix_workout_templates_routine_id'), 'workout_templates', ['routine_id'], unique=False)
    op.create_table('meal_entry_items',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('meal_entry_id', sa.String(length=26), nullable=False),
    sa.Column('food_id', sa.String(length=26), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('grams', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('sodium_mg', sa.Float(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['meal_entry_id'], ['meal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_entry_items_food_id'), 'meal_entry_items', ['food_id'], unique=False)
    op.create_index(op.f('ix_meal_entry_items_meal_entry_id'), 'meal_entry_items', ['meal_entry_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('template_id', sa.String(length=26), nullable=True),
    sa.Column('routine_id', sa.String(length=26), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('perceived_energy', sa.Integer(), nullable=True),
    sa.Column('bodyweight_kg', sa.Float(), nullable=True),
    sa.Column('total_volume_kg', sa.Float(), nullable=False),
    sa.Column('total_sets', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_deleted_at'), 'workout_sessions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workout_sessions_routine_id'), 'workout_sessions', ['routine_id'], unique=False)
    op.create_index(op.f('ix_workout_sessions_started_at'), 'workout_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workout_sessions_template_id'), 'workout_sessions', ['template_id'], unique=False)
    op.create_table('workout_template_exercises',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('workout_template_id', sa.String(length=26), nullable=False),
    sa.Column('exercise_id', sa.String(length=26), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('target_reps_min', sa.Integer(), nullable=False),
    sa.Column('target_reps_max', sa.Integer(), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('target_rir', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_template_id'], ['workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_template_exercises_exercise_id'), 'workout_template_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_template_exercises_workout_template_id'), 'workout_template_exercises', ['workout_template_id'], unique=False)
    op.create_table('set_entries',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('workout_session_id', sa.String(length=26), nullable=False),
    sa.Column('exercise_id', sa.String(length=26), nullable=False),
    sa.Column('template_exercise_id', sa.String(length=26), nullable=True),
    sa.Column('set_index', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('load_kg', sa.Float(), nullable=False),
    sa.Column('rir', sa.Float(), nullable=True),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('is_pr', sa.Boolean(), nullable=False),
    sa.Column('progression_label', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['template_exercise_id'], ['workout_template_exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_set_entries_exercise_id'), 'set_entries', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_set_entries_template_exercise_id'), 'set_entries', ['template_exercise_id'], unique=False)
    op.create_index(op.f('ix_set_entries_workout_session_id'), 'set_entries', ['workout_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_entries_workout_session_id'), table_name='set_entries')
    op.drop_index(op.f('ix_set_entries_template_exercise_id'), table_name='set_entries')
    op.drop_index(op.f('ix_set_entries_exercise_id'), table_name='set_entries')
    op.drop_table('set_entries')
    op.drop_index(op.f('ix_workout_template_exercises_workout_template_id'), table_name='workout_template_exercises')
    op.drop_index(op.f('ix_workout_template_exercises_exercise_id'), table_name='workout_template_exercises')
    op.drop_table('workout_template_exercises')
    op.drop_index(op.f('ix_workout_sessions_template_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_started_at'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_routine_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_deleted_at'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_meal_entry_items_meal_entry_id'), table_name='meal_entry_items')
    op.drop_index(op.f('ix_meal_entry_items_food_id'), table_name='meal_entry_items')
    op.drop_table('meal_entry_items')
    op.drop_index(op.f('ix_workout_templates_routine_id'), table_name='workout_templates')
    op.drop_index(op.f('ix_workout_templates_name'), table_name='workout_templates')
    op.drop_index(op.f('ix_workout_templates_deleted_at'), table_name='workout_templates')
    op.drop_table('workout_templates')
    op.drop_index(op.f('ix_session_tokens_user_id'), table_name='session_tokens')
    op.drop_index(op.f('ix_session_tokens_token_hash'), table_name='session_tokens')
    op.drop_index(op.f('ix_session_tokens_expires_at'), table_name='session_tokens')
    op.drop_table('session_tokens')
    op.drop_index(op.f('ix_routine_exercises_routine_id'), table_name='routine_exercises')
    op.drop_index(op.f('ix_routine_exercises_exercise_id'), table_name='routine_exercises')
    op.drop_table('routine_exercises')
    op.drop_index(op.f('ix_recipe_items_recipe_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_recipe_items_food_id'), table_name='recipe_items')
    op.drop_table('recipe_items')
    op.drop_index(op.f('ix_meal_template_items_meal_template_id'), table_name='meal_template_items')
    op.drop_index(op.f('ix_meal_template_items_food_id'), table_name='meal_template_items')
    op.drop_table('meal_template_items')
    op.drop_index(op.f('ix_meal_entries_template_id'), table_name='meal_entries')
    op.drop_index(op.f('ix_meal_entries_recipe_id'), table_name='meal_entries')
    op.drop_index(op.f('ix_meal_entries_photo_draft_id'), table_name='meal_entries')
    op.drop_index(op.f('ix_meal_entries_meal_type'), table_name='meal_entries')
    op.drop_index(op.f('ix_meal_entries_logged_at'), table_name='meal_entries')
    op.drop_index(op.f('ix_meal_entries_deleted_at'), table_name='meal_entries')
    op.drop_table('meal_entries')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_token_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_weight_entries_logged_at'), table_name='weight_entries')
    op.drop_index(op.f('ix_weight_entries_deleted_at'), table_name='weight_entries')
    op.drop_table('weight_entries')
    op.drop_index(op.f('ix_routines_name'), table_name='routines')
    op.drop_index(op.f('ix_routines_deleted_at'), table_name='routines')
    op.drop_table('routines')
    op.drop_index(op.f('ix_recipes_name'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_deleted_at'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_photo_analysis_drafts_status'), table_name='photo_analysis_drafts')
    op.drop_table('photo_analysis_drafts')
    op.drop_index(op.f('ix_meal_templates_name'), table_name='meal_templates')
    op.drop_index(op.f('ix_meal_templates_deleted_at'), table_name='meal_templates')
    op.drop_table('meal_templates')
    op.drop_index(op.f('ix_job_records_status'), table_name='job_records')
    op.drop_index(op.f('ix_job_records_job_type'), table_name='job_records')
    op.drop_index(op.f('ix_job_records_dedupe_key'), table_name='job_records')
    op.drop_index(op.f('ix_job_records_available_at'), table_name='job_records')
    op.drop_table('job_records')
    op.drop_index(op.f('ix_insight_snapshots_snapshot_date'), table_name='insight_snapshots')
    op.drop_table('insight_snapshots')
    op.drop_index(op.f('ix_idempotency_records_path'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_method'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_key'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_created_at'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_goals_metric_key'), table_name='goals')
    op.drop_index(op.f('ix_goals_deleted_at'), table_name='goals')
    op.drop_index(op.f('ix_goals_category'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.drop_index(op.f('ix_food_items_deleted_at'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_index(op.f('ix_export_records_status'), table_name='export_records')
    op.drop_table('export_records')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_deleted_at'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_app_users_username'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
